FAI-13036: Extend schema to ensure faros github source runs
faros-ai/faros-community-edition pull request #366
Opened 2024-10-03 20:38 UTC by chalenge

# Description

- Adds tables to ensure we can write all sources from Faros GitHub source
- Fixed migration v012, which had a file name typo hence didn't run
## Type of change
(Delete what does not apply)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# Checklist
(Delete what does not apply)
- [X] Have you checked that there aren't other open Pull Requests for the same update/change?
- [X] Have you lint your code locally before submission?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [X] Have you successfully run tests with your changes locally?

2024-10-03 20:40 UTC, thomas-gerber requested changes

2024-10-03 20:40 UTC, thomas-gerber commented on .env
> +# and in kube/base/faros/config
you need to follow those instructions for the test to pass @chalenge

2024-10-03 20:44 UTC, chalenge commented on .env
> +# and in kube/base/faros/config
Updated. Didn't think spaces would be an issue

2024-10-07 16:28 UTC, ypc-faros approved these changes

2024-10-07 18:48 UTC, thomas-gerber approved these changes
LGTM modulo what I asked @chalenge to check on SaaS/CE schema drift

2024-10-08 21:14 UTC, merged